[project]
name = "agno-multi-agent-systems"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agno>=2.4.8",
    "boto3>=1.42.41",
    "ddgs>=9.10.0",
    "python-dotenv>=1.2.1",
    "sqlalchemy>=2.0.46",
]
